### ISSUE TITLE
Research into Agenda and Cron Scheduling

### ISSUE THREAD

**Issue by Umang-Rajkarnikar** [RishiVaya/Lower_Earth_Orbiters#113]
Description:
The MIST application must schedule commands using a queue. Based on the date and time of the overpasses, a queue of tasks need to run which can be achieved through an asynchronous job.

Look into Agenda which is a node.js scheduling tool which also persists jobs to MongoDB:
https://hokify.github.io/agenda/agenda/6.x/

**Comment by quinnha** [comment]
Related: #109

**Comment by Umang-Rajkarnikar** [comment]
Scheduling flow

**Case 1**: Send to next available overpass
1. Send command from frontend to backend endpoint
2. Create scheduled request record in MongoDB Schedule table
   a. Check for next available overpass by aggregating all records and multiplying it by session timeout, then store it
       i. If somehow all overpasses are full, can either send err msg or create a record with the latest overpass date?

**Case 2**: Future scheduling
1. Send command from frontend to backend endpoint with date
2. Create scheduled request record in MongoDB Schedule table with given overpass date
   a. Check if the overpass date is full by aggregating all records and multiplying it by session timeout. If it is, return err msg else store it

**Job execution**:

When an overpass occurs for a satellite:
1. Satellite id will be used to query all schedules set for this overpass date, and the query shall sort it by creation date (asc).
Each schedule will be executed sequentially
2. For each execution, update status of schedule record and create log entry
3. If there are leftovers, stack them for the next overpass

**Comment by Umang-Rajkarnikar** [comment]
UML diagram describing relations between Satellite, Command (previously named as Scheduling), and Logs schemas.
https://drive.google.com/file/d/1PLmMVWE4ht9ASTp434nA2R-Oi-UvP6TZ/view?pli=1

**Operator Shceduling**
1. Schedule command sequence(s) for a satellite by providing execution time and command(s)
    a. Create schedule record in SCHEDULE Table and corresponding commands in COMMAND Table
2. Instant command sequence, treat as scheduled command sequence but the execution time is set to earliest overpass

**Setting up the queue**
Run job that checks if a satellite overpass will occur in the next 15 minutes, if it does:
- Query SCHEDULE Table and find all records
WHERE current date (e.g. Date.now()) + 15 minutes > executionTime SORTED by createdAt and priority and status == QUEUED
- For each schedule, store each command in queueCmd in the form of object:
{
		cmdId: string,
		command: string,
		delay: number,
		priority: number
}

**During the overpass:**
For each object in queueCmd:
1. Execute command
2. Update command record status
3. Record log

If there are leftovers, for each object in queueCmd:
- Update command record by decreasing priority. This is so that the scheduled commands for the next overpass run first
- The queueCmd should be empty after each overpass

**Comment by quinnha** [comment]
need access to the drive link, but some initial questions:

setting up the queue is only done once right? so as new overpasses are predicted (assume we run /getnextpasses or whatever api call) itll just add to the schedule db?

what if someone wants to run a schedule immediately/next? how will that work?

**Comment by quinnha** [comment]
uml looks good to me, should we have a schedule object which has a list of commands, with a total output log? this prevents operators from having to go into every single command, and instead see it at a glance -> could also be good for organizational purposes

**Comment by Umang-Rajkarnikar** [comment]
> uml looks good to me, should we have a schedule object which has a list of commands, with a total output log? this prevents operators from having to go into every single command, and instead see it at a glance -> could also be good for organizational purposes

Would each schedule obj represent an overpass date and it would have all commands executed for that overpass? Btw in the UML diagram, the Schedule schema was renamed to Commands

**Comment by Umang-Rajkarnikar** [comment]
Currently with the way it's set up, all the logs for an operator can be fetched based on the userId and satelliteId, but I think we can add in another relation with a Schedule schema. Each record represents an overpass date and each command record would also reference some overpass date, which shows the overpass date it was executed on

**Comment by quinnha** [comment]
yep sounds good to me

**Comment by Umang-Rajkarnikar** [comment]
Flow for frontend
<img width="1287" alt="image" src="https://github.com/RishiVaya/Lower_Earth_Orbiters/assets/59628796/5ba4a2e7-87a0-4965-aa96-dfed4a8a94ef">

**Comment by quinnha** [comment]
![image](https://github.com/RishiVaya/Lower_Earth_Orbiters/assets/35006641/8df1f893-5df3-46a0-a60d-d228add0dbd8)
thoughts on something like this for the satellite page? @Umang-Rajkarnikar

**Comment by quinnha** [comment]
![image](https://github.com/RishiVaya/Lower_Earth_Orbiters/assets/35006641/0255bc4c-2635-4f3f-9981-4e1eca413b8c)
and detailed display

**Comment by Umang-Rajkarnikar** [comment]
> ![image](https://private-user-images.githubusercontent.com/35006641/295355900-2450eb86-0b0d-40b2-89fb-79217f05ede7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTgyOTAsIm5iZiI6MTcwNDg1Nzk5MCwicGF0aCI6Ii8zNTAwNjY0MS8yOTUzNTU5MDAtMjQ1MGViODYtMGIwZC00MGIyLTg5ZmItNzkyMTdmMDVlZGU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDAzMzk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MThmOWQwZmU0ZmE4YTFjNjcwYTUwYzg2YTFkYmY5N2JmZDU5MzVjNzJmYmU3ZTFhMzM4MzY2YjhiYjY3ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IRca1DAl0hp5buxLTA_19NKQUZQnfNVo1b8y45wnchY) thoughts on something like this for the satellite page? @Umang-Rajkarnikar

Yeah that looks awesome! Really like the layout of information in this page

For the Schedule Queue section, that is showing the commands scheduled for the next three overpasses right? Also, was thinking if we should add a "View All" button in the bottom right of each schedule, what do you think?

**Comment by quinnha** [comment]
yea maybe a view all would make sense, and then our main action button would be add schedule? right now theres lots of ways for our user to go, but we can also confirm with austin and the crew for what their most commonly used action will be
